version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tech-challenge-fiap-product-mongodb
    environment:
      MONGO_INITDB_DATABASE: product_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeme123}
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - product-network

  tech-challenge-fiap-product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech-challenge-fiap-product
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-changeme123}@mongodb:27017/product_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - product-network

volumes:
  mongodb_data:

networks:
  product-network:
    driver: bridge