name: CD - Build, Quality and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-quality:
    name: Build and Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      
      - name: Build and Test
        run: mvn clean verify
      
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=LucasMachadoID2_tech-challenge-fiap-product \
            -Dsonar.organization=lucasmachadoid2 \
            -Dsonar.host.url=https://sonarcloud.io
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 1

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build-and-quality
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tech-challenge-fiap-product:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tech-challenge-fiap-product:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tech-challenge-fiap-product:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/tech-challenge-fiap-product:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/tech-challenge-fiap-product:buildcache,mode=max
